baseURL: "https://yixingzhao.com" 
title: Yixing Zhao | Waterloo BioStatistics PhD Student
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true


taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 2 
        - name: Contact
          url: contact/
          weight: 3
        - name: Courses
          url: courses/
          weight: 4
        - name: CV
          url: cv.pdf
          weight: 5 
        - name: Blog
          url: blog/
          weight: 6

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Yixing Zhao
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yixing Zhao
          subtitle: "I am a current PhD candidate in Biostatistics under the supervision of Liqun Diao. I completed a Bachelor of Mathematics in Computational Mathematics at the University of Waterloo in 2023, and then obtained a Master of Mathematics in Statistics from the University of Waterloo in 2024. My research interests are Bayesian methods and machine learning."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: papers/
            - name: Contact
              url: contact/
            - name: Courses
              url: courses/
            - name: CV
              url: cv.pdf
            - name: Blog
              url: blog/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: y679zhao@uwaterloo.ca
        - name: GitHub
          url: https://github.com/HG-KaiBai

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yixing Zhao"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
